# Generated by Django 5.2.1 on 2025-06-10 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='main_app.WrittenBy', to='main_app.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='formats',
            field=models.ManyToManyField(through='main_app.BookFormat', to='main_app.format'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(through='main_app.BookGenre', to='main_app.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editions', to='main_app.book'),
        ),
    ]
