# Generated by Django 5.2.1 on 2025-06-10 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_book_authors_alter_book_formats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendswith',
            options={'ordering': ['since']},
        ),
        migrations.AlterModelOptions(
            name='hasread',
            options={'ordering': ['-review_date']},
        ),
        migrations.AlterModelOptions(
            name='wantstoread',
            options={'ordering': ['-since']},
        ),
        migrations.AlterModelOptions(
            name='writtenby',
            options={},
        ),
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='book',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='friendswith',
            name='since',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friendswith',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendswith',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hasread',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hasread',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wantstoread',
            name='since',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='BookEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('changes_summary', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='main_app.book')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edit_date'],
            },
        ),
        migrations.DeleteModel(
            name='LSR',
        ),
    ]
