# Generated by Django 5.2.1 on 2025-06-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_chat_chatmessage_follow_delete_friendswith'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dark_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_public_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_friend_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_new_followers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_review_likes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Mexico_City', max_length=50),
        ),
    ]
